apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: rollingupdate
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: rollingupdate
  template:
      metadata:
        name: rollingupdate
        labels:
          app: rollingupdate
      spec:
        containers:
        - name: rollingupdate
          image: nginx:latest
